VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IRqmLayout"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
' code written by Mateusz Milewski
'
' mateusz.milewski@ gm.com
' FireFlakeHybrid
'
'
' ClassModule IEbalLayout
' ========================
'
' interface with 2 proc on changing daily layout

Public Sub RqmLayoutON()

End Sub

Public Sub RqmLayoutOFF()

End Sub

